name: Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install package dependencies
        run: yarn install
      
      - name: Install example app dependencies
        run: yarn example install

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck
